version: '3.1'

services:
  postgres:
    container_name: challenger
    image: postgres
    restart: always
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: "123"
    volumes:
      - postgres-vol:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "7000:5432"

volumes:
  postgres-vol: